### ISSUE TITLE
restaurer lugin escalade a la version compatible avec GLPI 10.0.10 

### ISSUE THREAD

**Issue by aminos8888** [pluginsGLPI/escalade#193]
Bonjour,
Me version GLPI est 10.0.10, le nouvelle version escalade 2.9.5 que j'ai mis a jour n'est pas compatible j'aimerai restaurer celle d'avant.
Il n y a aucun moyen de le faire, voir la capture ci-dessous:
![Capture d'écran 2024-05-15 141151](https://github.com/pluginsGLPI/escalade/assets/3728829/dff3e797-7196-4325-8075-013ff871e9d0)
merci pour votre support

**Comment by stonebuzz** [comment]
Hi
What is your GLPI version?

Best regards

**Comment by aminos8888** [comment]
Hi,
My version is GLPI 10.0.10

**Comment by stonebuzz** [comment]
The plugin indicates compatibility with all GLPI versions, but since version 2.9.5 the minimum GLPI version is 10.0.11. 

I've corrected compatibility through the marketplace so that version 2.9.5 is no longer available on GLPI versions later than 10.0.11.

To continue using the Escalade plugin in its latest version, you'll need to update GLPI (if only for security reasons).

Otherwise, you need to replace the plugin (in the marketplace folder) with version 2.9.4

Best regards

**Comment by aminos8888** [comment]
THANKS
If I understood correctly.
to continue using escalation with glpi 10.0.10 I must download an old version, the one before 2.9.4.
and replace the new plugin with the old one manually in the marketplace folder

**Comment by stonebuzz** [comment]
yep =)

but I strongly advise you to update your GLPI to the latest version

**Comment by aminos8888** [comment]
Thank you :)
can you please give the download link of the best plugin to install?
